// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Infrastructure.Data;

#nullable disable

namespace TodoApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908035242_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.Domain.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "En Progreso"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Completada"
                        });
                });

            modelBuilder.Entity("TodoApp.Domain.Models.Importancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Importancias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Baja"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Media"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Alta"
                        });
                });

            modelBuilder.Entity("TodoApp.Domain.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdImportancia")
                        .HasColumnType("int");

                    b.Property<int?>("IdTareaPadre")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FechaLimite")
                        .HasDatabaseName("IX_Tarea_FechaLimite");

                    b.HasIndex("IdEstado")
                        .HasDatabaseName("IX_Tarea_Estado");

                    b.HasIndex("IdImportancia")
                        .HasDatabaseName("IX_Tarea_Importancia");

                    b.HasIndex("IdTareaPadre");

                    b.ToTable("Tareas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Titulo_MinLength", "LEN(Titulo) >= 5");
                        });
                });

            modelBuilder.Entity("TodoApp.Domain.Models.Tarea", b =>
                {
                    b.HasOne("TodoApp.Domain.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TodoApp.Domain.Models.Importancia", "Importancia")
                        .WithMany()
                        .HasForeignKey("IdImportancia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TodoApp.Domain.Models.Tarea", null)
                        .WithMany("subtarea")
                        .HasForeignKey("IdTareaPadre")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Estado");

                    b.Navigation("Importancia");
                });

            modelBuilder.Entity("TodoApp.Domain.Models.Tarea", b =>
                {
                    b.Navigation("subtarea");
                });
#pragma warning restore 612, 618
        }
    }
}
